### ISSUE TITLE
如何添加分类和标签里面的内容？

### ISSUE THREAD

**Issue by jiangchengyike** [AlynxZhou/hexo-theme-aria#1]

**Comment by AlynxZhou** [comment]
分类和标签里面的内容是 hexo 自动生成的，创建了这两个页面之后用户没办法修改里面的内容。如果你指的是这两个页面是空的，你需要在写文章的时候修改文章的 front matter 里面对应的值，hexo 会自动收集起来归类。

**Comment by jiangchengyike** [comment]
我新建的一个文件，只有tag信息，没有categories信息，不知道为什么

**Comment by jiangchengyike** [comment]
已经解决，谢谢
