### ISSUE TITLE
commentjs头像显示大小的问题

### ISSUE THREAD

**Issue by Pyrrhax** [AlynxZhou/hexo-theme-aria#14]
我用这个主题搭建了自己的博客pyrrhax.com，发现commentjs评论区，显示的头像尺寸为所加载的头像图片原尺寸（比如图片尺寸很大，就会把旁边的东西挤到一边）。并且“去评论”按钮没有背景色，很难被找到。。
打开sh.alynx.xyz，审查元素进行对比，发现头像部分的CSS样式少了
.comments .commentjs .avatar-parent-child .avatar {
    width: 3em;
    height: 3em;
}
自己手动在index.styl中加入了
.comments 
  .commentjs 
    .avatar-parent-child 
      .avatar {
    width: 3em;
    height: 3em;
}
才恢复正常。。
目前还是一脸懵逼。。。不知道为什么会这样。。

**Comment by AlynxZhou** [comment]
是最新版本嘛？先拉取一下试试

**Comment by AlynxZhou** [comment]
在我这里访问你的网站是正常的。

![screenshot from 2018-08-15 21-40-29](https://user-images.githubusercontent.com/8444615/44151044-ed89854a-a0d3-11e8-9e7e-3b2d0e0f4f42.png)

你可能是 CSS 文件没有加载完全或者缓存的文件过期了，建议你 Ctrl-Shift-i 打开控制台之后右键点击左上角刷新按钮（浏览器地址栏左面那个），选择第三项 "Empty Cache and Hard Reload"（清除缓存并重新载入），看看是否解决了问题。如果没有，打开控制台的 Network 选项卡然后再右键第三项刷新一次，看看对应的文件（`index.css`）是否加载成功。

由于无法复现我先关闭了，有问题的话继续评论，我会接着看的。

**Comment by Pyrrhax** [comment]
不不不。。。我是用的最新版本，然后出现了问题。。自己手动改好的。如果我再拉取新版本。。就又出错了。。

**Comment by Pyrrhax** [comment]
我错了。。我刚刚拉了一下，还真好了。

**Comment by Pyrrhax** [comment]
可能最新版本，更（gèng）新了。。因为之前用的是昨天拉的。
不过我还有个问题能不能请教一下。。。为什么我那篇博客里面的表格没有变成表格。。而是直接显示文本出来了。。明明在各种markdown在线编辑网站都可以qwq

**Comment by AlynxZhou** [comment]
你是不是没有在上下留空行

**Comment by AlynxZhou** [comment]
![screenshot from 2018-08-16 12-20-34](https://user-images.githubusercontent.com/8444615/44188985-58dc7300-a153-11e8-81e7-f0565c04dfc8.png)

做了个这样的表格样式

**Comment by Pyrrhax** [comment]
NICE!
