### ISSUE TITLE
mathjax无法正常显示

### ISSUE THREAD

**Issue by jiangchengyike** [AlynxZhou/hexo-theme-aria#15]
你好，之前我这边的mathjax可以显示公式，但是最近又不可以了，不知道是怎么回事，我将global设置为true也不行。

**Comment by AlynxZhou** [comment]
![screenshot from 2018-08-16 13-05-04](https://user-images.githubusercontent.com/8444615/44189274-12881380-a155-11e8-9399-bf5b2a470e42.png)

![screenshot from 2018-08-16 13-05-42](https://user-images.githubusercontent.com/8444615/44189277-1caa1200-a155-11e8-9383-ba4e53f9d3eb.png)

我这里测试没有问题，建议你首先更新主题到最新版本，然后检查你使用的 MathJax CDN 是不是出现了问题无法成功加载文件，然后检查你自己公式的写法，按照文档，对于行内的公式，需要使用 `\\(` 和 `\\)` 围起来，然后如果出现了比如 `*` 这种 Markdown 中用到的符号，需要改写成 `\*` 进行转义，不然会被 Marked 先当成 Markdown 渲染（Markdown 是在 `hexo g` 时候渲染的，但是 MathJax 是在浏览器访问的时候才渲染）。

无法复现先关闭了，如果你还有问题，把你包含公式的那部份用代码块发上来，还有你的配置里关于 MathJax 的部分，我来试试复现。
