### ISSUE TITLE
如何配置主题的文章列表不要默认展开？

### ISSUE THREAD

**Issue by YangJiexian** [AlynxZhou/hexo-theme-aria#2]
如何配置主题的文章列表不要默认展开？

**Comment by AlynxZhou** [comment]
请仔细解释一下“不要默认展开”的含义，如果是指使用“阅读全文”截断的话，Hexo 中需要在你想截断的位置手动插入 `<!--more-->` 标签。

如果你是想只显示标题不显示文章内容（也不使用阅读全文），这个和主题的设计不一致，不打算实现。

**Comment by AlynxZhou** [comment]
比如说你有一个post，有两个自然段，你把这个标签复制到两段中间，首页就只会选择第一个了，这个不是主题负责的部分，至于auto_excerpt这个功能是hexo内置的吧，你去看站点的配置文件，不是主题的，里面有没有这个功能，如果开了主题不支持，你再来联系我。

**Comment by AlynxZhou** [comment]
好像不是hexo的，那我有空加上这个功能好了

**Comment by AlynxZhou** [comment]
@YangJiexian 添加了自动截断功能，你可以参照文档更新一下主题，然后设置这个功能。

**Comment by YangJiexian** [comment]
ok,多谢啦！已成功修改。
