### ISSUE TITLE
上传的md文件标题会多一个 #

### ISSUE THREAD

**Issue by RunjiLiu** [AlynxZhou/hexo-theme-aria#22]
# I Have Done Those and Need to Create a New Issue / 我确定我已经做过了下面这几步并确实需要创建一个新 Issue

- [x] Yes, I already updated my theme to the newest version as [docs](https://github.com/AlynxZhou/hexo-theme-aria#update-theme) and cleaned cache before testing (`hexo clean && hexo s`). / 是的，我已经按照 [文档](https://github.com/AlynxZhou/hexo-theme-aria/blob/master/README.zh_CN.md#%E6%9B%B4%E6%96%B0%E4%B8%BB%E9%A2%98) 把我的主题更新到最新版本了并在测试之前清除了缓存（`hexo clean && hexo s`）。
- [x] Yes, I already read [Hexo Docs page](https://hexo.io/docs/). / 是的，我已经查阅过 [Hexo 文档](https://hexo.io/zh-cn/docs/index.html) 了。
- [x] Yes, I already verified I found a theme problem, not a Hexo problem or because of my lack of Markdown usage and Hexo usage. / 是的，我已经确定我发现了一个主题的问题，而不是 Hexo 的问题或者因为我缺乏对于 Markdown 和 Hexo 用法的了解。
- [x] Yes, I already searched opening issues and not found related issues. / 是的，我查找过了未解决的 issue 并且没有发现类似的。

# Expected Behavior / 预期行为

 
上传markdown文件
# Actual Behavior / 实际行为

标题前面会出现’#‘
## Related Screenshots / 相关截图
![2019-01-07 2](https://user-images.githubusercontent.com/41376283/50756587-9d4de400-1297-11e9-8f96-c5f644828b59.png)

## Related Pages / 相关页面

# Steps to Reproduce / 重现步骤

1. N/A
2. N/A
3. N/A

# Related Configuration and Code / 相关配置和代码

## Site's `_config.yml` / 站点配置文件

```yml


```

## Theme's `_config.yml` / 主题配置文件

```yml

```

## Code / 代码

```

```

# Others / 其他

**Comment by AlynxZhou** [comment]
这是个 Feature，不是 Bug，`#` 其实是个超链接，点击可以直接定位到这个标题，方便给别人分享某个段落用的，如果你不想要可以尝试在 `source/css/custom.styl` 里加上这一段：

```stylus
.post-main {
  a.headerlink {
    &::before {
      content: "" !important;
    }
  }
}
```

我不太确定这个能不能生效，如果不能你再联系我，我告诉你别的办法。

**Comment by AlynxZhou** [comment]
顺便我看了一下你的网站，Markdown 的标题更多是用来表示结构的，不是用来表示样式的，所以不建议你用这个标题修改字号和字形，你可以直接写 HTML 标签并嵌入 style 来修改样式。

**Comment by RunjiLiu** [comment]
ok,可以生效，谢谢了。
