### ISSUE TITLE
一键复制功能

### ISSUE THREAD

**Issue by GreenHatHG** [AlynxZhou/hexo-theme-aria#23]
请问有没有一键复制代码块的功能

**Comment by AlynxZhou** [comment]
没有，不会写，而且我觉得需求不大…不好布局。

**Comment by AlynxZhou** [comment]
@GreenHatHG 昨晚到现在我琢磨了一下，把这功能集成进来了，但是是在我的 Hikaru 的主题上，一会我看看移植到 Hexo 主题试试，这个依赖生成器高亮代码块的布局，需要调整一下。

**Comment by AlynxZhou** [comment]
@GreenHatHG 试一下 <https://github.com/AlynxZhou/hexo-theme-aria/commit/4ba127b545fc4f3482695d3b6f130975ce4fb600> 这个最新的提交。

**Comment by AlynxZhou** [comment]
不需要配置，直接 `pull` 最新版本的主题应该就行。

**Comment by AlynxZhou** [comment]
等下，用这个 <https://github.com/AlynxZhou/hexo-theme-aria/commit/4fe59f9e8ee3f9bf863eb599e19baee84a1df8f6>，Hexo 开启行号和不开启行号布局差好多，得单独判断。

**Comment by GreenHatHG** [comment]
4fe59f9这个开启行号布局没有问题是么

**Comment by AlynxZhou** [comment]
最新的都没问题
