### ISSUE TITLE
自定义menu图标不能显示

### ISSUE THREAD

**Issue by GreenHatHG** [AlynxZhou/hexo-theme-aria#24]
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1g0hsigtjk1j30ek024t8y.jpg">
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1g0hsiwjxcyj30ux0g8goa.jpg">
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1g0hsje02n0j305d02h743.jpg">
这样好像不行，不能显示

**Comment by AlynxZhou** [comment]
你这版本不对吧，写的是4.4，内嵌的版本大概是5

**Comment by AlynxZhou** [comment]
在最新版里面这个叫 `<i class="far fa-hand-rock"></i>` 不是 `<i class="fa fa-hand-rock-o"></i>`
