### ISSUE TITLE
图片显示文章首

### ISSUE THREAD

**Issue by GreenHatHG** [AlynxZhou/hexo-theme-aria#25]
<img src="https://ws1.sinaimg.cn/large/0072Lfvtly1g0jzk4uk9qj30t00kfqln.jpg">
请问怎么实现这个效果，我按照下面来是不行的
[https://github.com/ppoffice/hexo-theme-icarus/issues/146](https://github.com/ppoffice/hexo-theme-icarus/issues/146)

**Comment by AlynxZhou** [comment]
你说啥呢？拿别的主题的设置往另一个主题上套想想就知道不行吧…设计的时候没考虑支持文章头图，因为和主题风格不符。

**Comment by GreenHatHG** [comment]
那请问你是怎么实现的，你的博客不是可以这样吗

**Comment by AlynxZhou** [comment]
？？？他说那个是头图，头图是不属于文章内容的，但我这个图是文章里的，你只要把图片插入到截断的 `<!--more-->` 之前，就会显示在主页里了。
