### ISSUE TITLE
如何限制显示图片的大小

### ISSUE THREAD

**Issue by GreenHatHG** [AlynxZhou/hexo-theme-aria#26]
开发者你好。
`<img src="190408/e.png" width="50%"></img>`
我使用了上述代码不能限制图片的大小，现在图片在博客上面显示太大，请问正确的语法是怎么样的，谢谢

**Comment by AlynxZhou** [comment]
给个截图看一下？这里width应该不能设置百分比。

**Comment by GreenHatHG** [comment]
typora显示图片
![typora显示图片](https://i.loli.net/2019/04/14/5cb3261dabcc0.png)
firefox显示的博客图片
![firefox显示的博客图片](https://i.loli.net/2019/04/14/5cb3261e57c22.png)
图片代码：
`<img src="190408/e.png" width="50%"></img>`

**Comment by AlynxZhou** [comment]
![Screenshot from 2019-04-15 08-02-14](https://user-images.githubusercontent.com/8444615/56101278-d2339c00-5f54-11e9-8c68-21776da2f682.png)
所以在 HTML5 里面你不能设置 width 为百分比，只能设置为像素，或者你可以在标签里写 style 改 css。
