### ISSUE TITLE
侧栏部件

### ISSUE THREAD

**Issue by FloatingMaple** [AlynxZhou/hexo-theme-aria#27]
你好，请问侧栏部件是否能够增加一些？例如把category list放在侧栏。
或者自己实现的话我应该如何修改呢

**Comment by AlynxZhou** [comment]
看看 `sidebar.njk` 的内容

**Comment by AlynxZhou** [comment]
我自己是不太想往侧栏添加分类标签之类的，因为空间有限，如果你想添加建议自己 fork 一个然后修改 `sidebar.njk`。
