### ISSUE TITLE
Mango

### ISSUE THREAD

**Issue by ghost** [AlynxZhou/hexo-theme-aria#31]
## 请问我可以用你的主题来搭建我的博客网站吗？谢谢

**Comment by AlynxZhou** [comment]
如果不行为什么我要把代码发到 GitHub 上，直接用就行了，建议顺便了解一下开源的含义。

**Comment by ghost** [comment]
谢谢，我大一的，感觉一学期下来没学到什么东西，准备写写博客慢慢积累，star走一波。
