### ISSUE TITLE
mathjax没有效果

### ISSUE THREAD

**Issue by jiangchengyike** [AlynxZhou/hexo-theme-aria#4]
我现在配置好了，但是没有渲染出数学表达式，请问还需要改什么么

**Comment by AlynxZhou** [comment]
能把控制台输出给我看看吗？

**Comment by jiangchengyike** [comment]
是运行hexo命令的还是网页里面的？我对这个不太懂

**Comment by AlynxZhou** [comment]
这个不是hexo管的范围，你用 chrome 或者 firefox 打开出问题的页面，然后按 F12 在侧面窗口选 console，看有没有红色的错误之类的。顺便为了加快加载速度，如果你不把 global 设成 true 的话不是每页都加载 MathJax 的（这玩意30M，实在是太难搞了），你可能需要检查一下有没有给用了公式的 post 加 `mathjax: true` 这个文件头，不开启 global 的话必须有这个文件头页面才会包含 mathjax。

**Comment by AlynxZhou** [comment]
<https://docs.mathjax.org/en/latest/tex.html#tex-and-latex-math-delimiters> 我个人是不太懂 LaTeX 的，不过按照 MathJax 的文档来看似乎它不会把 `$` 当作标记符？尝试使用 `\(...\)` 或者 `$$...$$` 试试呢？

**Comment by AlynxZhou** [comment]
啊不对，我尝试了一下，单个 `$` 之间是可以的！我这里没有问题！所以你可能需要考虑找一个国内的 CDN 服务器……

**Comment by jiangchengyike** [comment]
请问你添加的是哪个cdn，我这里换了个国内的还是不行，不知道是不是我的格式问题，能发一下你的格式么？

**Comment by AlynxZhou** [comment]
就他官网文档里那个呀，话说你只要看一下浏览器上是不是一直转圈圈就知道是不是加载完了…

**Comment by AlynxZhou** [comment]
格式的话就直接把cdn的网址（不是标签）复制到cdn选项，然后在页面添加文件头就好了呀。公式的话，你去找我发的那个页面吧，测试的可以是 `$a < b$` 这种。话说你测试的是什么？发给我试试行吗。

**Comment by AlynxZhou** [comment]
哈哈，虽然不太明白，但是看起来不是我的问题。解决了就太好啦。

**Comment by AlynxZhou** [comment]
另外推荐更新一下主题哈，你现在用这个版本footer布局在移动端有bug，现在的我已经修复了

**Comment by jiangchengyike** [comment]
恩恩，已经更新，非常感谢
