### ISSUE TITLE
你好, 我想问下highlight高亮语法的问题

### ISSUE THREAD

**Issue by siyuansixsixsix** [AlynxZhou/hexo-theme-aria#6]
![image](https://user-images.githubusercontent.com/21104451/41519106-afddef46-72f8-11e8-8532-078e70d60e9c.png)
![image](https://user-images.githubusercontent.com/21104451/41519116-bb426790-72f8-11e8-9d4b-5c8b5df9a021.png)
我的配置如上, 但是页面上并没有highlight生效, 且页面上也没有给高亮的类名添加 hljs- 的前缀

**Comment by siyuansixsixsix** [comment]
页面上显示的高亮也是原生的样式 控制台也没有报错

**Comment by AlynxZhou** [comment]
先clean之后再生成试试，如果还不行就在代码块标注一下语言

**Comment by siyuansixsixsix** [comment]
好的, 谢谢, 这个代码块标注语言能说下吗。。。这个不知道怎么标注

**Comment by AlynxZhou** [comment]
比如你用反引号表示一段代码，那就在你代码块开始的那几个反引号后面写上语言名字比如
```
\`\`\`JavaScipt
console.log("Hello world!);
\`\`\`
```

**Comment by AlynxZhou** [comment]
去掉反斜杠，我不知道怎么阻止它被转义，大概这样？
````
```JavaScript
console.log("Hello world");
```
````

**Comment by siyuansixsixsix** [comment]
好的
![image](https://user-images.githubusercontent.com/21104451/41525158-a1663cb0-7312-11e8-811e-4686c8ef19a8.png)
这样解决了, 谢谢
