### ISSUE TITLE
HyperComments接入没几天就开始收钱了  之前多说接入没几天就关闭了……

### ISSUE THREAD

**Issue by jingb** [AlynxZhou/hexo-theme-aria#7]
桑心，接入没几天就开始收钱了  
之前多说接入没几天就关闭了  真的是报警了

**Comment by AlynxZhou** [comment]
不在乎gfw换disqus，在乎换commentjs，反正我已经习惯了

**Comment by AlynxZhou** [comment]
顺便提醒一下代码仓库issue不是当贴吧用的…除非是像commentjs那样的…所以我给你关闭了…
