### ISSUE TITLE
commonjs评论功能,头像样式错乱

### ISSUE THREAD

**Issue by halu886** [AlynxZhou/hexo-theme-aria#8]
commonjs评论功能,头像样式错乱
[具体请点击这里](https://halu886.github.io/2018/06/28/%E5%AE%9E%E4%B9%A0%E6%80%BB%E7%BB%93/)
:flushed:

**Comment by AlynxZhou** [comment]
先确定一下，你用的是最新的版本吗？不是的话先pull然后再hexo clean再生成一次看看。

**Comment by AlynxZhou** [comment]
窝修复了，你拉取最新的版本吧
